import type { Metadata } from "next"
import { Geist, Geist_Mono, Outfit , Poppins } from "next/font/google"
import "./globals.css"
import { AuthProvider } from "@/Context/AuthProvider"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // choose weights you use
  variable: '--font-poppins',          // optional for CSS variable usage
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Project Vibe",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  className={outfit.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} antialiased dark`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  )
}
